name: Deploy Ma-Dyang Backend

on:
  push:
    branches: [ main ] # CI/CD jalan setiap kamu push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: '203.194.114.74'
          username: 'mie'
          port: 22
          password: 'MieenakPol@!'
          script: |
            echo 'MieenakPol@!' | sudo -S -u www-data git -C /var/www/PT3_Mie_Madyang reset --hard origin/main
            echo 'MieenakPol@!' | sudo -S -u www-data git -C /var/www/PT3_Mie_Madyang pull origin main
            
            # --- Deploy Backend ---
            echo 'MieenakPol@!' | sudo -S -u www-data composer --working-dir=/var/www/PT3_Mie_Madyang/backend install --no-dev --optimize-autoloader
            echo 'MieenakPol@!' | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan migrate --force
            echo 'MieenakPol@!' | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan config:cache
            echo 'MieenakPol@!' | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan route:cache
            echo 'MieenakPol@!' | sudo -S systemctl restart php8.2-fpm
            
            # --- Deploy Frontend ---
            echo 'MieenakPol@!' | sudo -S -u www-data bash -c 'cd /var/www/PT3_Mie_Madyang/frontend && npm install'
            echo 'MieenakPol@!' | sudo -S -u www-data bash -c 'cd /var/www/PT3_Mie_Madyang/frontend && npm run build'
            echo 'MieenakPol@!' | sudo -S -u www-data pm2 restart frontend
            
            echo "Anjay, Deploy Frontend & Backend Berhasil, Lur!"
