name: Deploy Ma-Dyang

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S git -C /var/www/PT3_Mie_Madyang reset --hard origin/main
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S git -C /var/www/PT3_Mie_Madyang pull origin main
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chown -R $USER:www-data /var/www/PT3_Mie_Madyang

            # --- Deploy Backend ---
            cd /var/www/PT3_Mie_Madyang/backend && composer install --no-dev --optimize-autoloader
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan migrate --force
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan config:cache
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan route:cache
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S -u www-data php /var/www/PT3_Mie_Madyang/backend/artisan storage:link || true
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chown -R www-data:www-data /var/www/PT3_Mie_Madyang/backend/storage /var/www/PT3_Mie_Madyang/backend/bootstrap/cache
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S systemctl restart php8.2-fpm

            # --- Deploy Frontend ---
            cd /var/www/PT3_Mie_Madyang/frontend && npm install && npm run build
            pm2 restart mie-madyang-frontend || pm2 start npm --name "mie-madyang-frontend" --cwd "/var/www/PT3_Mie_Madyang/frontend" -- start

            echo "Deploy Frontend & Backend Berhasil!"
